Implement role for 14-sles
adfinis/ansible-collection-maintenance pull request #61
Opened 2024-04-23 13:34 UTC by pierreoxs

2024-05-03 15:20 UTC, s3lph requested changes
Please review the way this project (ab-)uses Ansible task results:
https://github.com/adfinis/ansible-collection-maintenance/blob/main/README.md?plain=1#L10-L16

(Yes, I know it can be a bit counterintuitive...)

2024-05-03 15:20 UTC, s3lph commented on roles/maintenance_14_sles/tasks/main.yml
> +  when: "'Not Registered' in suseconnect_status_output.stdout"
I'd remove the two debug tasks and simply change the command task directly emit the changed status:
```suggestion
  changed_when: "'Not Registered' in suseconnect_status_output.stdout"
```
That way we don't have an unnecessary indirection (first save the output, then print something else based on it), and we get the actual output of SUSEConnect back.

2024-05-03 15:20 UTC, s3lph commented on roles/maintenance_14_sles/tasks/main.yml
> +  when: zypper_refresh_output.rc == 0
What purpose does this task serve? This never gets printed, as it is neither changed nor failed.
I'd much rather expect the playbook to fail if the rc is nonzero.

2024-05-14 12:23 UTC, pierreoxs commented
@s3lph A new commit is available for review

2024-05-14 14:47 UTC, s3lph commented
@pierreoxs you can simply use the "Re-request review" button at the top right:
![image](https://github.com/adfinis/ansible-collection-maintenance/assets/5564491/9a60116e-0f43-4f30-859a-f8278a9b5b1d)

2024-05-14 15:07 UTC, s3lph requested changes

2024-05-17 13:38 UTC, pierreoxs commented
Hey @s3lph , new commit available and I used the "Re-request review" button :)

2024-05-21 09:26 UTC, s3lph requested changes
Only these two minor things, then I think this can be merged.

2024-05-21 09:26 UTC, s3lph commented on roles/maintenance_14_sles/tasks/main.yml
> +  when: apparmor_status_output is succeeded
On doing some [additional checking](https://manpages.ubuntu.com/manpages/focal/en/man8/aa-status.8.html), you can simply check the rc of aa-status.
```suggestion
  changed_when: "task.rc != 0"
  failed_when: "task.rc == 4"  # Insufficient permission to check AA policies.
```

2024-05-21 09:26 UTC, s3lph commented on roles/maintenance_14_sles/tasks/main.yml
> +  failed_when: "{{ zypper_refresh_output.rc != 0 }}"
If you're not using the result of the task in another task, you don't actually need to register the task result again. All tasks using the `*task` "template" already register their result in the `task` variable, which can be used in e.g. `changed_when` or `failed_when`.

```suggestion
  failed_when: "task.rc != 0"
```

2024-05-21 12:04 UTC, s3lph commented on roles/maintenance_14_sles/tasks/main.yml
> +  failed_when: "{{ zypper_refresh_output.rc != 0 }}"
Wait, there actually is no `.rc` at all in the result of `community.general.zypper`. Have you tested this code?
I think `failed_when` can be omitted entirely in this case, just letting it fail when zypper says it failed.
```suggestion
```

2024-05-21 15:09 UTC, s3lph approved these changes

2024-05-22 08:24 UTC, merged

2024-05-22 08:28 UTC, s3lph commented
Released as 0.1.24.